name: Restream M3U8

on:
  workflow_dispatch:

jobs:
  restream:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Install FFmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: Restream M3U8
        run: |
          ffmpeg -re -i "https://love.sayob28681.workers.dev/lx-origin/sd-thaifilm_720/chunks.m3u8" \
          -c copy \
          -f hls \
          -hls_time 6 \
          -hls_list_size 5 \
          -hls_flags delete_segments \
          stream.m3u8

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: hls-stream
          path: |
            *.m3u8
            *.ts
